### ISSUE TITLE
Some issues about the performance of O2U

### ISSUE THREAD

**Issue by ningkp** [hjimce/O2U-Net#1]
we employ the resnet101 model and perform the experiments in the CIFAR100 dataset. We didn't make any changes to the source code. However, we can't reproduce your results.
![image](https://user-images.githubusercontent.com/27044503/95697196-78f31880-0c70-11eb-8191-82a44f6d1557.png)

The red part is the result of my running, which records the training results of the model in stage three. Moreover, the performance of "coteaching" is also not well.

**Comment by hjimce** [comment]
@ningkp  --transforms=true, is significant impact on performance. did  you set？

**Comment by ningkp** [comment]
OK, it works.

**Comment by ruirui88** [comment]
when  the batchsize of second stage was set to 16, the train loss value wad getting into NAN.(I   employ the 9-layer CNN model and perform the experiments in the CIFAR10 dataset). Why is this?

**Comment by ScarlettLeeBieber** [comment]
> we employ the resnet101 model and perform the experiments in the CIFAR100 dataset. We didn't make any changes to the source code. However, we can't reproduce your results.
> ![image](https://user-images.githubusercontent.com/27044503/95697196-78f31880-0c70-11eb-8191-82a44f6d1557.png)
> 
> The red part is the result of my running, which records the training results of the model in stage three. Moreover, the performance of "coteaching" is also not well.

could you please send me your repo-code,thx

**Comment by Ffmydy** [comment]
everyone，I can't find model file

**Comment by ScarlettLeeBieber** [comment]
您好，新闻中心已经收到新闻稿。
